#!/usr/bin/env sh

set -e

case "$1" in
  cpu_serial_get)
    grep Serial /proc/cpuinfo | sed -E 's/Serial\s+:\s+//'
    ;;
  cpu_temp_read)
    cat /sys/class/thermal/thermal_zone0/temp
    ;;
  hostname_get)
    hostname
    ;;
  hostname_set)
    hostnamectl hostname "$2"
    sed -E -i "s/127.0.1.1\t\t.+/127.0.1.1\t\t$2/" /etc/hosts
    ;;
  ip_config_get)
    if [ "$#" -ne "2" ]
    then
      echo "ip_config_get: 2 arguments required, $# provided"
      exit 1
    fi
    DEVICE="$2"
    dhcp="$(           nmcli -g ipv4.method con show "$DEVICE" )"
    case "$dhcp" in
      auto)
        dhcp=TRUE
        ;;
      manual)
        dhcp=FALSE
        ;;
    esac
    address="$(        nmcli -g IP4.ADDRESS    con show "$DEVICE" | sed 's/ | / /g' )"
    address_manual="$( nmcli -g ipv4.addresses con show "$DEVICE" | sed 's/,/ /g'   )"
    gateway="$(        nmcli -g IP4.GATEWAY    con show "$DEVICE" | sed 's/ | / /g' )"
    dns="$(            nmcli -g IP4.DNS        con show "$DEVICE" | sed 's/ | / /g' )"
    dns_manual="$(     nmcli -g ipv4.dns       con show "$DEVICE" | sed 's/,/ /g'   )"
    for addr1 in $address
    do
      is_dhcp=true
      for addr2 in $address_manual
      do
        if [ "$addr1" = "$addr2" ]
        then
          is_dhcp=false
        fi
      done
      if [ "$is_dhcp" = "true" ]
      then
        if [ -z "$address_dhcp" ]
        then
          address_dhcp="$addr1"
        else
          address_dhcp="$address_dhcp $addr1"
        fi
      fi
    done
    for dns1 in $dns
    do
      is_dhcp=true
      for dns2 in $dns_manual
      do
        if [ "$dns1" = "$dns2" ]
        then
          is_dhcp=false
        fi
      done
      if [ "$is_dhcp" = "true" ]
      then
        if [ -z "$dns_dhcp" ]
        then
          dns_dhcp="$dns1"
        else
          dns_dhcp="$dns_dhcp $dns1"
        fi
      fi
    done

    echo "$dhcp\n$address_manual\n$address_dhcp\n$gateway\n$dns_manual\n$dns_dhcp"
    ;;
  ip_config_set)
    if [ "$#" -ne "6" ]
    then
      echo "ip_config_set: 6 arguments required, $# provided"
      exit 1
    fi
    DEVICE="$2"
    DHCP="$3"
    ADDRESS="$4"
    GATEWAY="$5"
    DNS="$6"

    case "$DHCP" in
      TRUE)
        nmcli con mod "$DEVICE" ipv4.method auto ipv4.addresses "$ADDRESS" ipv4.gateway "$GATEWAY" ipv4.dns "$DNS"
        ;;
      FALSE)
        [ -n "$ADDRESS" ] && nmcli con mod "$DEVICE" ipv4.addresses "$ADDRESS"
        [ -n "$GATEWAY" ] && nmcli con mod "$DEVICE" ipv4.gateway   "$GATEWAY"
        [ -n "$DNS"     ] && nmcli con mod "$DEVICE" ipv4.dns       "$DNS"
        nmcli con mod "$DEVICE" ipv4.method manual || exit 1
        ;;
      *)
        echo "ip_config_set: DHCP must be TRUE or FALSE"
	exit 2
	;;
    esac
    nmcli con up "$DEVICE"
    ;;
  mac_address_get)
    if [ "$#" -ne "2" ]
    then
      echo "mac_address_get: 2 arguments required, $# provided"
      exit 1
    fi
    nmcli -e n -g GENERAL.HWADDR dev show "$2"
    ;;
  ntp_config_get)
    #timedatectl show-timesync -p SystemNTPServers -p FallbackNTPServers -p ServerName
    NTP=$(timedatectl show -P NTP)
    case "$NTP" in
      yes)
        NTP=TRUE
        ;;
      no)
        NTP=FALSE
        ;;
    esac
    if [ -f /etc/systemd/timesyncd.conf.d/server.conf ]
    then
      Servers=$(grep -o -P '(?<=NTP=)(.+)' /etc/systemd/timesyncd.conf.d/server.conf)
    fi
    if [ -f /etc/systemd/timesyncd.conf.d/fallback.conf ]
    then
      Fallback=$(grep -o -P '(?<=FallbackNTP=)(.+)' /etc/systemd/timesyncd.conf.d/fallback.conf)
    fi
    echo "$NTP\n$Servers\n$Fallback"
    ;;
  ntp_config_set)
    if [ "$#" -ne "4" ]
    then
      echo "ntp_config_set: 4 arguments required, $# provided"
      exit 1
    fi
    NTP="$2"
    SERVER="$3"
    FALLBACK="$4"
    case "$SERVER" in
      "")
      ;;
      "-")
        rm -f /etc/systemd/timesyncd.conf.d/server.conf
        ;;
      *)
        echo "[Time]\nNTP=$SERVER" > /etc/systemd/timesyncd.conf.d/server.conf
        ;;
    esac
    case "$FALLBACK" in
      "")
      ;;
      "-")
        rm -f /etc/systemd/timesyncd.conf.d/fallback.conf
        ;;
      *)
        echo "[Time]\nFallbackNTP=$FALLBACK" > /etc/systemd/timesyncd.conf.d/fallback.conf
        ;;
    esac
    case "$NTP" in
      TRUE)
        timedatectl set-ntp true
        systemctl restart systemd-timesyncd
        ;;
      FALSE)
        timedatectl set-ntp false
        ;;
    esac
    ;;
  os_reboot)
    reboot
    ;;
  rts_restart)
    systemctl restart codesyscontrol
    ;;
  timezone_get)
    timedatectl show -P Timezone
    ;;
  timezone_set)
    timedatectl --no-ask-password set-timezone "$2"
    ;;
  watchdog_write)
    echo "$2" > /sys/kernel/wp360-pmuc/watchdog
    ;;
  *)
    echo "No command or invalid command"
    exit 1
    ;;
esac
