#!/usr/bin/env sh

set -e

case "$1" in
  cpu_temp_read)
    cat /sys/class/thermal/thermal_zone0/temp
    ;;
  ip_config_set)
    if [ "$#" -ne "6" ]
    then
      echo "ip_config_set: 6 arguments required, $# provided"
      exit 1
    fi
    DEVICE="$2"
    DHCP="$3"
    ADDRESS="$4"
    GATEWAY="$5"
    DNS="$6"

    case "$DHCP" in
      TRUE)
        nmcli con mod "$DEVICE" ipv4.method auto ipv4.addresses "$ADDRESS" ipv4.gateway "$GATEWAY" ipv4.dns "$DNS"
        ;;
      FALSE)
        [ -n "$ADDRESS" ] && nmcli con mod "$DEVICE" ipv4.addresses "$ADDRESS"
        [ -n "$GATEWAY" ] && nmcli con mod "$DEVICE" ipv4.gateway   "$GATEWAY"
        [ -n "$DNS"     ] && nmcli con mod "$DEVICE" ipv4.dns       "$DNS"
        nmcli con mod "$DEVICE" ipv4.method manual || exit 1
        ;;
      *)
        echo "ip_config_set: DHCP must be TRUE or FALSE"
	exit 1
	;;
    esac
    nmcli con up "$DEVICE"
    ;;
  os_reboot)
    reboot
    ;;
  rts_restart)
    systemctl restart codesyscontrol
    ;;
  timezone_get)
    timedatectl show --property=Timezone
    ;;
  timezone_set)
    timedatectl --no-ask-password set-timezone "$2"
    ;;
  watchdog_write)
    echo "$2" > /sys/kernel/wp360-pmuc/watchdog
    ;;
  ftp)
    IN=$(mktemp -u /run/user/1000/codesys-bridge.XXXXXXXX)
    OUT=$(mktemp -u /run/user/1000/codesys-bridge.XXXXXXXX)
    mkfifo "$IN" "$OUT"
    /usr/lib/wp360-codesys-bridge/wp360-codesys-bridge-rs "$@" < "$IN" > "$OUT" & disown
    echo "$IN"
    echo "$OUT"
    ;;
  *)
    echo "No command or invalid command"
    exit 1
    ;;
esac
